### ISSUE TITLE
Create Statistics Design

### ISSUE THREAD

**Issue by arifulbgt4** [arifulbgt4/Marketplace#16]
**widget:** `StatisticsCard`
[StatisticsCard design](https://www.figma.com/file/1vbUL0QSZrE5fZlBhhTnVS/Dream-House?type=design&node-id=1873-60586&mode=design&t=iJ8RWWmDQP7QuCHX-4)

**widget:** `StatisticsCardGroup`
[StatisticsCard Group Design](https://www.figma.com/file/1vbUL0QSZrE5fZlBhhTnVS/Dream-House?type=design&node-id=1873-60585&mode=design&t=iJ8RWWmDQP7QuCHX-4)

**Comment by Mdjuealhossain** [comment]
solved
