### ISSUE TITLE
Mobile view of Listing Search Filter

### ISSUE THREAD

**Issue by arifulbgt4** [arifulbgt4/Marketplace#86]

**Comment by Mdjuealhossain** [comment]
![Screenshot_10](https://github.com/arifulbgt4/Marketplace/assets/123495777/a4d3457e-34f9-4077-883a-fe0860609821)
![Screenshot_11](https://github.com/arifulbgt4/Marketplace/assets/123495777/1d05f791-37f3-48af-8e90-0569beed7a3e)
